#*******************************************************************************
# Copyright (c) 2024 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
---

apiVersion: v1
kind: Pod
metadata:
  namespace: openpass
  name: cephfs-test
spec:
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: openpass-cache-storage
      mountPath: /cache-storage
  securityContext:
    fsGroupChangePolicy: "OnRootMismatch"
    runAsUser: 1002870000
    runAsGroup: 1002870000
    seLinuxOptions:
      level: s0:c4,c54
  volumes:
  - name: openpass-cache-storage
    persistentVolumeClaim:
      claimName: openpass-cache-storage

