jenkins:
  nodes:
  - permanent:
      labelString: "windows windows10"
      launcher:
        jnlp:
          vmargs: "-Xmx512m"
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      mode: EXCLUSIVE
      name: "b9qls-windows-10"
      nodeDescription: "Windows 10 Pro N, no login session, hosted on Azure"
      remoteFS: "C:\\Users\\genie.simopenpass\\jenkins_agent"
      retentionStrategy: "always"
      nodeProperties:
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
unclassified:
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "gitlab-api-token"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "gitlab.eclipse.org"
      readTimeout: 10
      url: "https://gitlab.eclipse.org"
  gitLabServers:
    Servers:
    - credentialsId: "gitlab-personal-access-token"
      name: "gitlab.eclipse.org"
      serverUrl: "https://gitlab.eclipse.org"