jenkins:
  nodes:
  - permanent:
      name: "6mnjf-windows-10-vnc"
      nodeDescription: "Windows 10 Pro N, with permanent VNC, hosted on Azure"
      labelString: "windows permanent-vnc windows10"
      remoteFS: 'C:\jenkins_agent'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            internalDir: "remoting"
            failIfWorkDirIsMissing: false
      nodeProperties:
      - toolLocation:
          locations:
          - home: 'C:\ProgramData\chocolatey\lib\ant\apache-ant-1.10.5'
            key: "hudson.tasks.Ant$AntInstallation$DescriptorImpl@apache-ant-1.9.6"
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      name: "b9h15-macos10.15"
      nodeDescription: "macOS 10.15 (Catalina), no login session, hosted on MacStadium"
      labelString: "macos macos-10.15"
      remoteFS: '/Users/genie.releng/jenkins_agent/'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          credentialsId: "b9h15-macos10.15-bot-ssh"
          host: "208.52.161.179"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Mo4/c9Hn6sA594UEGHVxCKbu/QtophcofQIfrX1cJwkxfx/MGjMhllrWw49SfpNPh/VOlR4T7r3xeFq9TM+sDXAii54deTENpqg5q1uBOx9hi+7W8MhKpuJEhwL37kTQHSjcnIcexpm76Tbyd3QtHU3xQzMCjfREfqIAWkWaKbdzNVu1JJRcwqRXDDzPNkoLfYUZtdQi/XiROlX5zYh3/GpQctGkL3y8mdkeUY7RGUDKTjd7osAK59IR30H2KFRfewey9YnMnIKM0cokA8t3KDvAwmXFLQ+iAxG1RFLZQ88iz7agO1clNYFR3+2ersXcMu/AZUoA6sBsBXIJ9419"
      nodeProperties:
      - envVars:
          env:
          - key: "PATH"
            value: '$HOME/.cargo/bin:$PATH'
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      labelString: "macos macos-10.15"
      launcher:
        ssh:
          credentialsId: "ta9y0-macos10.15-bot-ssh"
          host: "207.254.46.148"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCejyvfy3TfWh2CwKcEwj3BdLRb5ZpCw1k846vwpq/RzKEpIWFXarfH3KcDSDFUXQFSxxDCOokbfvPYxG+MyqmkQZ+g8nAahVX07rKIZu7AudHVPmYNOr8+iwKst38MuBB77UEKWwIaAov8UcM4bC6xPGc7SDVW59bMa151GN/dSDKHqTgKz2vMS62tdUG4D/bVYVYzmwSDOs85wnsX+oZe8TXABEt94jy10uDpgSkABdzNl/0m/C1boSIi3hOBrWuIk676PNj2lcUWz69SSUlmFElI7q9Mo+1TxuA0KQxy9D87mkRQ6lesZv/+CQJMhVuIso+APktrQ9uw3RhAbGoVq3MtANEoy3yv005HKIxnsVhUhkSCB1/EFSerbVBLndVXqY/3R7NgJDI0kbYg8VLLRWCoALveiO40Ss7tiHrTHXY2hFBsrhAzPTCZGLUbCjVc6tN+at1hjXhSJoB0h5uInywgMc1TfiJapihvrFoJlU+OhkJ/+oP6BgwVWDohiGE="
      mode: EXCLUSIVE
      name: "ta9y0-macos-10.15"
      nodeDescription: "macOS 10.15 (Catalina), with login session, hosted on MacStadium"
      nodeProperties:
      - envVars:
          env:
          - key: "JAVA_HOME"
            value: "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"
          - key: "PATH"
            value: "/usr/local/bin/:/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
      numExecutors: 1
      remoteFS: "/Users/genie.releng/jenkins_agent/"
      retentionStrategy: "always"
  - permanent:
      name: "rs68g-win10"
      nodeDescription: "Windows 10 Pro, hosted on Azure"
      labelString: "windows"
      remoteFS: 'C:\Users\genie.releng\ci'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "13.68.249.87"
          port: "22"
          credentialsId: "rs68g-win10-ssh"
          javaPath: "\"C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.292.10-hotspot\\bin\\java.exe\""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAkHWAKiWv/T3uaCBj8RdbPR4BW3GBdb5Digq4lpwnFc5xCLCZ/Wke6GBEBlai+zJndjm5sNYgKAAGUOFvW1t0ZCFxgS+uZ+tu2eyDoGyCAvS+XzbzN4pEGf3x/2GJE2aWoesrdx/Uhc/8J3cZG04Fy1SsllW36j4e/20PnZaCtPRBuU/9ZlX4pUDKIUDV+7ejOTTViAzxV0IqUQagiKLv1rxgkRQRgy49+oszYbTFmO7Sqy8L20sSRpSjO0eym6CTpbdjJSm70ZjlJNFocwREmlISNtdPPzY56NWQKf6qpzTlw94zZGVV/0WNdapn3pWS3OLIttVB1C1f1nHBdwvmooFgFiTJzfWaqY9wZFy+jNDi8BHHauLYySIh2PT65XWltnnJcwPM/87nk0hESuBglq3580mGbqoqYmoYhVOsJgn0r0HOHoCsfrUkk9EbUzuUh4TmbR9d6c+zrXe/p6XW8MNNoD1FC+IpruUiEIK9sJ25LAdeXP0hupL9SbddlCc="
      nodeProperties:
      - envVars:
          env:
          - key: "JAVA_HOME"
            value: 'C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot'
          - key: "PATH"
            value: 'C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Users\SSHD\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\bin'
          - key: "VS90_HOME"
            value: 'C:\Program Files (x86)\Microsoft Visual Studio\2019'
          - key: "VS90COMNTOOLS"
            value: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools'
      - toolLocation:
          locations:
          - home: 'C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin\mvn.cmd'
            key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@apache-maven-latest"
          - home: 'C:\ProgramData\chocolatey\bin\ant.bat'
            key: "hudson.tasks.Ant$AntInstallation$DescriptorImpl@apache-ant-1.9.6"
          - home: 'C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin\java'
            key: "hudson.model.JDK$DescriptorImpl@jdk1.8.0-latest"
          - home: 'C:\tools\cygwin\bin\git'
            key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      name: "zyt5z-centos7"
      nodeDescription: "Dedicated agent for performance tests, hosted on Azure"
      labelString: "performance docker-build"
      remoteFS: '/home/genie.releng/jenkins'
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "13.72.66.232"
          port: "22"
          credentialsId: "7b792838-4358-45dd-8309-e47b8a10e3c2"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCg6mNlOLk+bA8MY+gyttjCmVujsq0I/Bjvur/eon8Rrg4AHt+ug37NiFX1hknY3WyOrWSMS/2iyxJlgAByYAQth0FKh+d441PSafVan5H3jI0+nCLGCkYEtNpSrvKH1jjHKybtYX6zGQscEcNA74KxHPPDPnvp14kpWIFnt4mhC1uqbfbQf0eY5lJeMwPrpR+RwAEYJu/zk+LITuh5na9h1c77ENc9OUjTsmFMW7S1bLkx7v0PRpZeSmY0AXnHZ0aWH0KqU4AMe/gRkB+JTDJzJeks9vFko3yGVpuC4ePzbr5df9junbN6WiUf1bs33t0hGKvzVzPQSJ9YpDECFhI7"
      nodeProperties:
      - toolLocation:
          locations:
          - home: '/usr/bin/ant'
            key: "hudson.tasks.Ant$AntInstallation$DescriptorImpl@apache-ant-1.9.6"
          - home: '/usr/bin/mvn'
            key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@apache-maven-latest"
          - home: '/usr/bin/java'
            key: "hudson.model.JDK$DescriptorImpl@jdk1.8.0-latest"
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      name: "ppc64le-build"
      labelString: "ppcbuild"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "ppcle-buildTest"
      labelString: "ppctest ppcbuild"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "ppcle-test"
      labelString: "ppctest"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "aarch64-swt"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "centos-aarch64-1"
      labelString: "aarch64 arm64"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "centos-aarch64-2"
      labelString: "aarch64 arm64"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "centos-aarch64-3"
      labelString: "aarch64 arm64"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      name: "centos-aarch64-4"
      labelString: "aarch64 arm64"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/swtbuild/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
