jenkins:
  nodes:
  - permanent:
      name: "laeubisoft-build-node"
      nodeDescription: "Debian Bullseye 11 (64 bit) dynamic build node hosted by https://läubisoft.gmbh/en/"
      labelString: "linux, centos-8"
      remoteFS: '/home/buildnode'
      numExecutors: 4
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "109.239.48.216"
          port: "22"
          credentialsId: "laeubisoft-build-node-ssh"
          javaPath: ""
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd4o3WN4gawJbTvdrRjGW+tkpsHDUI7YriUiqm3/WfxzLXtWuJIiMl1GK3iofdxGWbWShEGeMHOy+8Yedy1u3jVTCO9RIW0M2d9Xxt4ub4jiCtESIBowpFdvj/14ZNbmGGE81PGTs+d57OrJ98T4ERK89MVbo/NQnA1Gzo93g2U0jkwkBk1O2CpKk6VzU4/ctsx7ekE+ZUvtXCRyTtSIX9eY8DTAznAw54DSUG0M5yWRzBRHQKwA+AtSTn3W2AQc6ZnBJYOdcI9dt/DfJ2+ohNqqDRviqDz7mk/k9Nh0YnPnEAceGAhm6wtAG0Zr5ZzRamxgyvoiSSh6c9BhDWZfGPIfHU0+NfEJryCclZdy6MAXylhfcGcnf4xigIZuGq+JugSLvVpJFgNEVKFAJFMPwR1JsuPwqt67jVT+2eDxxFbRQ8yI/O44QUFceUxdbFwcLeVxNtmqqx2bWMrMMuh7GiFMHZdQKUo1Wi6LFloqjCSIOqT4A9AVWHL+Wi9f4kIbs="
