jenkins:
  nodes:
  - permanent:
      labelString: "docker-build"
      launcher:
        ssh:
          credentialsId: "f3c8f3db-205e-4c99-9fbf-bb1da9e804a0"
          host: "52.191.195.224"
          jvmOptions: "-Xmx256m -Xms256m"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDL8Aa786HyCSHYcj/dSwRpaO5als+/j4YxsbGbuXVZsKsVhJLHZvnihntnvPter9UdodsPF/RjnJXdUsKar1qExhq0uVMPgXSEQlUPd7incDz/cL/yfWEYX1N7PL9cevtYfySTmNpoa7I0khrrfReiR4wr4BbX2CaTE0QAVHYJf5qtylqay3mf7HX1oCjpzp+FbAV5e+RY+rjRg5qdhP9fXVH35cdQh0OhRt1Kr8rrmENdJyyU9ZrLMgIAinfhvmx6anOPIu5MLz+awdfn1/uMkQguWX8Smurs3WYsVvdFwfq5t0PgAUrrOKXcTL/rLAXGeqL1OFdPAWlvs97hMsyn"
      mode: EXCLUSIVE
      name: "mlv8w-ubuntu1804"
      nodeDescription: "4vCPU, 16GB RAM, Hosted @ Azure"
      remoteFS: "/home/genie.infra/jenkins-agent"
      numExecutors: 2
      nodeProperties:
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      name: "ort-vm1"
      remoteFS: "/home/genie.infra"
      launcher:
        ssh:
          credentialsId: "ort-ssh-bot"
          host: "20.104.233.12"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkH1ET4ScUfV5JHHr7f7dOg4jHg09SL2Q03ST6oAmC5yxmU52uu8vhUZRM5H5zjrW4ml7/U4s+J3LyUHNtcQq5xqBrQCDc2uSXUTFeShp3FeehHRvvOzlJqSANvQj+0Qdxb/aU0lxAYXaLsRy+HEH75aSceTXYDFvVjygteBApVFAaTCNYlDNPsxMUQ1ZKi7cy7DPT1w6PVpGO+9i7WXHkMCJlhOLf6ivJWgH5NtcHJMAxs7fGHYPjn8rUJlSAY/Hg1bT5JcGAdNWxsaCmKMucaGBeHz2E+hXtx6k4ye5fJqlFuWkxfWyJSewmoNrilACl9XKp5mPbVZyCZCDJCtVYkT6gf3nm5bTiSfIBb5fLM1eVKssa2PNcEW7sajRKEpw6GKcD0a1gj1ERbZapVWk42AD9TCIeaT8SniZrq60n5E/SVRBQvoCArdLIQgfm4zflUsH/gFeMFMV/PvQ6vrbRCd+fhbnaRWFVOpUUwwMaM+8OXCbS9XOPge8B2wqOVqk="
      mode: EXCLUSIVE
      retentionStrategy: "always"
      numExecutors: 2

      