jenkins:
  nodes:
  - permanent:
      labelString: "macos macos-10.12"
      launcher:
        ssh:
          credentialsId: "b9h15-macos10.12-bot-ssh"
          host: "208.52.161.179"
          jvmOptions: "-Xmx256m"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Mo4/c9Hn6sA594UEGHVxCKbu/QtophcofQIfrX1cJwkxfx/MGjMhllrWw49SfpNPh/VOlR4T7r3xeFq9TM+sDXAii54deTENpqg5q1uBOx9hi+7W8MhKpuJEhwL37kTQHSjcnIcexpm76Tbyd3QtHU3xQzMCjfREfqIAWkWaKbdzNVu1JJRcwqRXDDzPNkoLfYUZtdQi/XiROlX5zYh3/GpQctGkL3y8mdkeUY7RGUDKTjd7osAK59IR30H2KFRfewey9YnMnIKM0cokA8t3KDvAwmXFLQ+iAxG1RFLZQ88iz7agO1clNYFR3+2ersXcMu/AZUoA6sBsBXIJ9419"
          workDir: "/Users/genie.justj/jenkins_agent/cache"
      name: "b9h15-macos10.12"
      mode: EXCLUSIVE
      numExecutors: 1
      remoteFS: "/Users/genie.justj/jenkins_agent/"
      retentionStrategy: "always"
      nodeProperties:
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
  - permanent:
      labelString: "windows windows10"
      launcher:
        jnlp:
          vmargs: "-Xmx256m"
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      name: "mp23n-windows-10"
      mode: EXCLUSIVE
      nodeDescription: "Windows 10 Pro N, no login session, hosted on Azure"
      nodeProperties:
      - envVars:
          env:
          - key: "Path"
            value: "C:\\tools\\cygwin\\bin;$Path;"
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"
      numExecutors: 1
      remoteFS: "C:\\Users\\genie.justj\\jenkins_agent"
      retentionStrategy: "always"
  - permanent:
      labelString: "linux aarch64"
      name: "f5cjn-project-provided-aarch64"
      nodeDescription: "Agent provided by the project"
      remoteFS: "/home/justj/build"
      numExecutors: 1
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
  - permanent:
      labelString: "macos macos-11 arm64"
      launcher:
        ssh:
          credentialsId: "w8qlf-macos11-arm64-bot-ssh"
          host: "208.52.170.174"
          jvmOptions: "-Xmx256m"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6+qT5aiFFqU70gw+d9+ZJN3oF/9yWStUtJfFIqboLDMWv/+L+1a8nOaobwT8U867Vwwwo0IvErq4eL+5IUXiNBdEu501WL82pfVMU3C509dRpkNqAT9Ymu3cLiPWhJ6BM9r5cCyaGIWYwsNTmvkLO2WRSt20b3TaQxhzyEewuI97OpoZPQCo2EIJqaOjnlynmbyhJjkJ98B10BCcaUbtKjyEhKXv2OmqpGf61or+mfmBEfOrW2HrE3mbE/ZRgPqb5nT/q6C7ObhVA/L0oGG+Gy1DSJnqSN2vy+kWsPAfGcI/1hh9xOS3wiJorEc3hvZYWH3PgyU5KwyRNAoB1LXVE/JyLtmcL36uwkLLcVROJtcVw6j3vSZgFFp7LiUEiYSVtwqwm74dlD/W7qO9pKEWQDltywk8NwqTTvhvSN9WXDMtSrRFfuRYJEVQquu5SHxTJLzQ2v/T+CRAD3WMKbTEILY+d7wOJrPNoxLbVQ+/joE96opoCI1BlgGchF3Q66hM="
      mode: EXCLUSIVE
      name: "w8qlf-macos11-arm64"
      remoteFS: "/Users/genie.justj/jenkins"
      retentionStrategy: "always"