name: Build JIRO instances
on:
  push:
    branches: 
      - '*'
jobs:
  build-jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: jiro
      - uses: actions/checkout@v4
        with:
          repository: eclipse-cbi/jiro-agents
          path: jiro-agents
      - uses: actions/checkout@v4
        with:
          repository: eclipse-cbi/jiro-masters
          path: jiro-masters
      - uses: actions/checkout@v4
        with:
          repository: yasammez/hbs-cli
          ref: ed85bd9e10f54b23331a36b51a6dd4e4134fb9c1
          path: hbs-cli
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
#          cache: 'npm'
#          cache-dependency-path: hbs-cli/package-lock.json
      - name: 'Install hbs'
        run: |
          npm ci
        working-directory: 'hbs-cli'
      - name: 'Install required software'
        run: |
          #sudo apt-get update
          sudo apt-get install jq
          sudo apt-get install pass
          set -x;
          #npm ci github:yasammez/hbs-cli#ed85bd9e10f54b23331a36b51a6dd4e4134fb9c1
          echo $PATH
          hbs --help
          hbs --version
          alias hbs="npx github:yasammez/hbs-cli#ed85bd9e10f54b23331a36b51a6dd4e4134fb9c1 --"
          hbs --version
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          #brew update
          brew install jsonnet
          brew install yq
      - name: 'Build instance'
        env:
          HOME: ./myHome
          CBI_HOME: ./myCBIHome
        run: |
          set -x
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          alias hbs="npx hbs-cli"
          hbs --version
          mkdir -p "${HOME}/.cbi"
          echo '{"password-store": {"cbi-dir": "~/.password-store/cbi"}}' > "${HOME}/.cbi/config"
          #make image_eclipse.platform
          
          ./build/build-image.sh instances/eclipse.platform
          which hbs
          where hbs
          cat instances/    .platform/target/jenkins/configuration.yml
        working-directory: jiro
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jenkins-config
          path: |
            jiro/instances/eclipse.platform
      - name: commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add * --all
          git commit -m 'Re-build'
          git push -f origin HEAD:rebuild-changes
        working-directory: jiro
